[project]
name = "portfolio-service"
version = "0.1.0"
description = "A Model Context Protocol server implementing popular broker api's"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
 "aiohttp>=3.11.8",
 "mcp>=1.0.0",
 "pandas>=2.2.3",
 "pydantic>=2.10.2",
 "python-dotenv>=1.0.1",
 "requests>=2.32.3",
 "retry>=0.9.2",
]
[[project.authors]]
name = "Itay Verkh"
email = "iverkh@lightricks.com"

[build-system]
requires = [ "hatchling",]
build-backend = "hatchling.build"

[project.scripts]
portfolio-service = "portfolio_service.server:main"
