[project]
name = "fin-agents-servers"
version = "0.1.0"
description = "A Model Context Protocol server providing market data"
requires-python = ">=3.10"
dependencies = []

[[project.authors]]
name = "Itay Verkh"
email = "itay1542@gmail.com"

[tool.uv.workspace]
members=[
    "brokerage_service",
    "market_data_service",
    "research_service",
]

[tool.uv.sources]
market_data_service = { workspace = true }
research_service = { workspace = true }
brokerage_service = { workspace = true }
